apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring-contrast-app
  labels:
    app: java-spring-contrast-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-spring-contrast-app
  template:
    metadata:
      labels:
        app: java-spring-contrast-app
    spec:
      containers:
      - name: java-spring-contrast-app
        image: java_spring_contrast_appimg:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
