apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-demo-service
spec:
  selector:
    app: springboot-k8s-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
